#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pyjwt
Version  : 2.3.0
Release  : 65
URL      : https://files.pythonhosted.org/packages/1d/8e/01bdcfdbb352daaba8ea406d9df149c5bba7dbf70f908d4fa4c269fe6a08/PyJWT-2.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/1d/8e/01bdcfdbb352daaba8ea406d9df149c5bba7dbf70f908d4fa4c269fe6a08/PyJWT-2.3.0.tar.gz
Summary  : JSON Web Token implementation in Python
Group    : Development/Tools
License  : MIT
Requires: pypi-pyjwt-license = %{version}-%{release}
Requires: pypi-pyjwt-python = %{version}-%{release}
Requires: pypi-pyjwt-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-py
BuildRequires : pypi-pytest
BuildRequires : pypi-pytest_runner
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
=====

%package license
Summary: license components for the pypi-pyjwt package.
Group: Default

%description license
license components for the pypi-pyjwt package.


%package python
Summary: python components for the pypi-pyjwt package.
Group: Default
Requires: pypi-pyjwt-python3 = %{version}-%{release}

%description python
python components for the pypi-pyjwt package.


%package python3
Summary: python3 components for the pypi-pyjwt package.
Group: Default
Requires: python3-core
Provides: pypi(pyjwt)

%description python3
python3 components for the pypi-pyjwt package.


%prep
%setup -q -n PyJWT-2.3.0
cd %{_builddir}/PyJWT-2.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1642466478
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pyjwt
cp %{_builddir}/PyJWT-2.3.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pyjwt/bc48b3f80bfc08458a1f78bb2b49c6de2b41010f
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pyjwt/bc48b3f80bfc08458a1f78bb2b49c6de2b41010f

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
